require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../../node_modules/@capacitor/browser'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  # Optional: Keep assertDeploymentTarget(installer) if it's a necessary function
  # assertDeploymentTarget(installer) 
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # These build settings are NOT needed for frameworks and must be removed 
      # to stop Xcode from looking for a profile.
      config.build_settings.delete('PROVISIONING_PROFILE_SPECIFIER')
      config.build_settings.delete('PROVISIONING_PROFILE')
      config.build_settings.delete('PRODUCT_BUNDLE_IDENTIFIER')
      
      # Keep the manual signing style and identity settings consistent
      config.build_settings['CODE_SIGN_STYLE'] = 'Manual'
      config.build_settings['DEVELOPMENT_TEAM'] = 'J6MWBCBLW7'
      config.build_settings['CODE_SIGN_IDENTITY'] = 'Apple Distribution'
      
      # For Pod targets, which are generally frameworks, we often want to 
      # disable the resource bundle generation if it's causing issues.
      config.build_settings['ENABLE_PREVIEWS'] = 'NO'
      config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-O'
    end
  end
end
